### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by onlynishant** [HebiRobotics/QuickBuffers#35]
Hi,

I am trying to use quickbuf with my Google Adx protobuf file but getting `java.lang.StackOverflowError`.
https://developers.google.com/authorized-buyers/rtb/downloads/openrtb-proto
https://developers.google.com/authorized-buyers/rtb/downloads/openrtb-adx-proto

command used: 
```
/Users/test/protoc-21.12-osx-aarch_64/bin/protoc --quickbuf_out=indent=4,java8_optional=true,input_order=quickbuf:.  *.proto
```

Error:
```
Exception in thread "main" java.lang.StackOverflowError
	at com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.newStackOverflowError0(StackOverflowCheckImpl.java:328)
	at com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.newStackOverflowError(StackOverflowCheckImpl.java:324)
	at com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.throwNewStackOverflowError(StackOverflowCheckImpl.java:304)
	at com.oracle.svm.core.graal.jdk.SubstrateArraycopySnippets.boundsCheck(SubstrateArraycopySnippets.java:117)
	at com.oracle.svm.core.graal.jdk.SubstrateArraycopySnippets.doArraycopy(SubstrateArraycopySnippets.java:94)
	at java.lang.String.getBytes(String.java:4477)
	at java.lang.AbstractStringBuilder.putStringAt(AbstractStringBuilder.java:1720)
	at java.lang.AbstractStringBuilder.putStringAt(AbstractStringBuilder.java:1724)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:583)
	at java.lang.StringBuilder.append(StringBuilder.java:179)
	at us.hebi.quickbuf.generator.TypeRegistry.resolveMessageType(TypeRegistry.java:87)
	at us.hebi.quickbuf.generator.TypeRegistry.resolveJavaTypeFromProto(TypeRegistry.java:77)
	at us.hebi.quickbuf.generator.RequestInfo$FieldInfo.getTypeName(RequestInfo.java:445)
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
	... <SAME LINE>
	... <SAME LINE>
	... <SAME LINE>
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
	at us.hebi.quickbuf.generator.TypeRegistry.hasRequiredFieldsInHierarchy(TypeRegistry.java:130)
--quickbuf_out: protoc-gen-quickbuf: Plugin failed with status code 1.
```

**Comment by ennerf** [comment]
The `Value` message in the `Struct` proto has recursive message definition in [struct.proto#L73-L76](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto#L73-L76), which is not compatible with eagerly allocated types. 

The import comes from [AdxExt](https://developers.google.com/authorized-buyers/rtb/downloads/openrtb-adx-proto), but as far as I can tell it's not even using it. You should be able to just comment out the import line.

I'll add a more useful error message.

**Comment by onlynishant** [comment]
> You should be able to just comment out the import line.

It's being used. Got these error after commenting `import "google/protobuf/struct.proto";`
```
DoubleClickOpenRTBExtension.proto:189:12: ".google.protobuf.Value" is not defined.
DoubleClickOpenRTBExtension.proto:399:12: ".google.protobuf.Value" is not defined.
```

> Also: Extensions are currently not directly supported either, so I'm not sure whether QuickBuffers is usable for you.

Yes, i realized it after posting the issue. I will try something else.

Thanks.

**Comment by ennerf** [comment]
Sorry for that. Support for recursive messages could be added pretty quickly, but Extensions would probably take ~2 days to support properly. That's hard to justify for something we don't have an internal use case for.

**Comment by ennerf** [comment]
I did some experiments and was able to add preliminary support for recursive message definitions and embedding extensions. 

It'll take more work and testing before I can release it, but here are some messages generated with the latest snapshot if you want to try it out: [openrtb-quickbuf-snapshot-8132db6.zip](https://github.com/HebiRobotics/QuickBuffers/files/10455996/openrtb-quickbuf-snapshot-8132db6.zip) . The extension fields are embedded directly in the extended message and look like normal fields.

**Comment by onlynishant** [comment]
thanks @ennerf. I will try it and update you.
